on:
  workflow_dispatch:
  workflow_call:

name: "Release prod"

jobs:
  release-prod:
    uses: ./.github/workflows/upload_assets.yml
    with:
      aws-region: us-east-2
      domain: www.diginfra.khulnasoft.com
      diginfra-dashboard-api-endpoint: https://dashboard.api.diginfra.khulnasoft.com
      diginfra-dashboard-endpoint: https://infra-dashboard.khulnasoft.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      DIGINFRA_DOCS_API_TOKEN: ${{ secrets.DIGINFRA_DOCS_API_TOKEN }}
